name: ASP.NET Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    
    runs-on: 
        - self-hosted
        - windows

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    
    - name: Restore Packages
      run: nuget restore CDN.sln
    
    - name: Build solution
      run: msbuild CDN.sln -t:rebuild -property:Configuration=Release -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true -p:SkipInvalidConfigurations=true -p:PackageLocation="${{ github.workspace }}/deploy"

  deploy:
    needs: build
    runs-on: [self-hosted windows]
    
    steps:    
    - name: Deploy to IIS
      run: msdeploy -verb:sync -source:package="${{ github.workspace }}\deploy\CDM.zip" -dest:auto -setParam:name=`"IIS Web Application Name`",value=`"CDN`"